/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/CreateMatchTrial_request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



CreateMatchTrial_request::CreateMatchTrial_request()
{
    m_VariableIsSet = false;
}

CreateMatchTrial_request::~CreateMatchTrial_request()
{
}

void CreateMatchTrial_request::validate()
{
    // TODO: implement validation
}

web::json::value CreateMatchTrial_request::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_VariableIsSet)
    {
        val[utility::conversions::to_string_t(U("variable"))] = ModelBase::toJson(m_Variable);
    }

    return val;
}

bool CreateMatchTrial_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("variable"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("variable")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ScalarOrVector> refVal_setVariable;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVariable);
            setVariable(refVal_setVariable);
        }
    }
    return ok;
}

void CreateMatchTrial_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_VariableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("variable")), m_Variable));
    }
}

bool CreateMatchTrial_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("variable"))))
    {
        std::shared_ptr<ScalarOrVector> refVal_setVariable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("variable"))), refVal_setVariable );
        setVariable(refVal_setVariable);
    }
    return ok;
}

std::shared_ptr<ScalarOrVector> CreateMatchTrial_request::getVariable() const
{
    return m_Variable;
}

void CreateMatchTrial_request::setVariable(const std::shared_ptr<ScalarOrVector>& value)
{
    m_Variable = value;
    m_VariableIsSet = true;
}

bool CreateMatchTrial_request::variableIsSet() const
{
    return m_VariableIsSet;
}

void CreateMatchTrial_request::unsetVariable()
{
    m_VariableIsSet = false;
}
}
}
}
}


