/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/MatchTrialStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

MatchTrialStatus::eMatchTrialStatus toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("evaluating")))
        return MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_EVALUATING;
    if (val == utility::conversions::to_string_t(U("evaluator_failed")))
        return MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_EVALUATOR_FAILED;
    if (val == utility::conversions::to_string_t(U("scorer_failed")))
        return MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_SCORER_FAILED;
    if (val == utility::conversions::to_string_t(U("scoring")))
        return MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_SCORING;
    if (val == utility::conversions::to_string_t(U("success")))
        return MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_SUCCESS;
    return {};
}

EnumUnderlyingType fromEnum(MatchTrialStatus::eMatchTrialStatus e)
{
    switch (e)
    {
    case MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_EVALUATING:
        return U("evaluating");
    case MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_EVALUATOR_FAILED:
        return U("evaluator_failed");
    case MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_SCORER_FAILED:
        return U("scorer_failed");
    case MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_SCORING:
        return U("scoring");
    case MatchTrialStatus::eMatchTrialStatus::MatchTrialStatus_SUCCESS:
        return U("success");
    default:
        break;
    }
    return {};
}
}

MatchTrialStatus::MatchTrialStatus()
{
}

MatchTrialStatus::~MatchTrialStatus()
{
}

void MatchTrialStatus::validate()
{
    // TODO: implement validation
}

web::json::value MatchTrialStatus::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool MatchTrialStatus::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void MatchTrialStatus::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool MatchTrialStatus::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

MatchTrialStatus::eMatchTrialStatus MatchTrialStatus::getValue() const
{
   return m_value;
}

void MatchTrialStatus::setValue(MatchTrialStatus::eMatchTrialStatus const value)
{
   m_value = value;
}


}
}
}
}


