/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/MatchTrialEvaluation.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



MatchTrialEvaluation::MatchTrialEvaluation()
{
    m_StatusIsSet = false;
    m_Error = utility::conversions::to_string_t("");
    m_ErrorIsSet = false;
    m_ObjectiveIsSet = false;
    m_ConstraintIsSet = false;
    m_InfoIsSet = false;
    m_Feasible = false;
    m_FeasibleIsSet = false;
    m_StartedAt = utility::datetime();
    m_StartedAtIsSet = false;
    m_FinishedAt = utility::datetime();
    m_FinishedAtIsSet = false;
}

MatchTrialEvaluation::~MatchTrialEvaluation()
{
}

void MatchTrialEvaluation::validate()
{
    // TODO: implement validation
}

web::json::value MatchTrialEvaluation::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_StatusIsSet)
    {
        val[utility::conversions::to_string_t(U("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_ErrorIsSet)
    {
        val[utility::conversions::to_string_t(U("error"))] = ModelBase::toJson(m_Error);
    }
    if(m_ObjectiveIsSet)
    {
        val[utility::conversions::to_string_t(U("objective"))] = ModelBase::toJson(m_Objective);
    }
    if(m_ConstraintIsSet)
    {
        val[utility::conversions::to_string_t(U("constraint"))] = ModelBase::toJson(m_Constraint);
    }
    if(m_InfoIsSet)
    {
        val[utility::conversions::to_string_t(U("info"))] = ModelBase::toJson(m_Info);
    }
    if(m_FeasibleIsSet)
    {
        val[utility::conversions::to_string_t(U("feasible"))] = ModelBase::toJson(m_Feasible);
    }
    if(m_StartedAtIsSet)
    {
        val[utility::conversions::to_string_t(U("startedAt"))] = ModelBase::toJson(m_StartedAt);
    }
    if(m_FinishedAtIsSet)
    {
        val[utility::conversions::to_string_t(U("finishedAt"))] = ModelBase::toJson(m_FinishedAt);
    }

    return val;
}

bool MatchTrialEvaluation::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<RunnerStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("error"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("error")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setError;
            ok &= ModelBase::fromJson(fieldValue, refVal_setError);
            setError(refVal_setError);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("objective"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("objective")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ScalarOrVector> refVal_setObjective;
            ok &= ModelBase::fromJson(fieldValue, refVal_setObjective);
            setObjective(refVal_setObjective);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("constraint"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("constraint")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ScalarOrVector> refVal_setConstraint;
            ok &= ModelBase::fromJson(fieldValue, refVal_setConstraint);
            setConstraint(refVal_setConstraint);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("info"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("info")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setInfo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInfo);
            setInfo(refVal_setInfo);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("feasible"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("feasible")));
        if(!fieldValue.is_null())
        {
            bool refVal_setFeasible;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFeasible);
            setFeasible(refVal_setFeasible);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("startedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("startedAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setStartedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStartedAt);
            setStartedAt(refVal_setStartedAt);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("finishedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("finishedAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setFinishedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFinishedAt);
            setFinishedAt(refVal_setFinishedAt);
        }
    }
    return ok;
}

void MatchTrialEvaluation::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("status")), m_Status));
    }
    if(m_ErrorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("error")), m_Error));
    }
    if(m_ObjectiveIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("objective")), m_Objective));
    }
    if(m_ConstraintIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("constraint")), m_Constraint));
    }
    if(m_InfoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("info")), m_Info));
    }
    if(m_FeasibleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("feasible")), m_Feasible));
    }
    if(m_StartedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("startedAt")), m_StartedAt));
    }
    if(m_FinishedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("finishedAt")), m_FinishedAt));
    }
}

bool MatchTrialEvaluation::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("status"))))
    {
        std::shared_ptr<RunnerStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("error"))))
    {
        utility::string_t refVal_setError;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("error"))), refVal_setError );
        setError(refVal_setError);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("objective"))))
    {
        std::shared_ptr<ScalarOrVector> refVal_setObjective;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("objective"))), refVal_setObjective );
        setObjective(refVal_setObjective);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("constraint"))))
    {
        std::shared_ptr<ScalarOrVector> refVal_setConstraint;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("constraint"))), refVal_setConstraint );
        setConstraint(refVal_setConstraint);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("info"))))
    {
        std::shared_ptr<Object> refVal_setInfo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("info"))), refVal_setInfo );
        setInfo(refVal_setInfo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("feasible"))))
    {
        bool refVal_setFeasible;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("feasible"))), refVal_setFeasible );
        setFeasible(refVal_setFeasible);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("startedAt"))))
    {
        utility::datetime refVal_setStartedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("startedAt"))), refVal_setStartedAt );
        setStartedAt(refVal_setStartedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("finishedAt"))))
    {
        utility::datetime refVal_setFinishedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("finishedAt"))), refVal_setFinishedAt );
        setFinishedAt(refVal_setFinishedAt);
    }
    return ok;
}

std::shared_ptr<RunnerStatus> MatchTrialEvaluation::getStatus() const
{
    return m_Status;
}

void MatchTrialEvaluation::setStatus(const std::shared_ptr<RunnerStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool MatchTrialEvaluation::statusIsSet() const
{
    return m_StatusIsSet;
}

void MatchTrialEvaluation::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t MatchTrialEvaluation::getError() const
{
    return m_Error;
}

void MatchTrialEvaluation::setError(const utility::string_t& value)
{
    m_Error = value;
    m_ErrorIsSet = true;
}

bool MatchTrialEvaluation::errorIsSet() const
{
    return m_ErrorIsSet;
}

void MatchTrialEvaluation::unsetError()
{
    m_ErrorIsSet = false;
}
std::shared_ptr<ScalarOrVector> MatchTrialEvaluation::getObjective() const
{
    return m_Objective;
}

void MatchTrialEvaluation::setObjective(const std::shared_ptr<ScalarOrVector>& value)
{
    m_Objective = value;
    m_ObjectiveIsSet = true;
}

bool MatchTrialEvaluation::objectiveIsSet() const
{
    return m_ObjectiveIsSet;
}

void MatchTrialEvaluation::unsetObjective()
{
    m_ObjectiveIsSet = false;
}
std::shared_ptr<ScalarOrVector> MatchTrialEvaluation::getConstraint() const
{
    return m_Constraint;
}

void MatchTrialEvaluation::setConstraint(const std::shared_ptr<ScalarOrVector>& value)
{
    m_Constraint = value;
    m_ConstraintIsSet = true;
}

bool MatchTrialEvaluation::constraintIsSet() const
{
    return m_ConstraintIsSet;
}

void MatchTrialEvaluation::unsetConstraint()
{
    m_ConstraintIsSet = false;
}
std::shared_ptr<Object> MatchTrialEvaluation::getInfo() const
{
    return m_Info;
}

void MatchTrialEvaluation::setInfo(const std::shared_ptr<Object>& value)
{
    m_Info = value;
    m_InfoIsSet = true;
}

bool MatchTrialEvaluation::infoIsSet() const
{
    return m_InfoIsSet;
}

void MatchTrialEvaluation::unsetInfo()
{
    m_InfoIsSet = false;
}
bool MatchTrialEvaluation::isFeasible() const
{
    return m_Feasible;
}

void MatchTrialEvaluation::setFeasible(bool value)
{
    m_Feasible = value;
    m_FeasibleIsSet = true;
}

bool MatchTrialEvaluation::feasibleIsSet() const
{
    return m_FeasibleIsSet;
}

void MatchTrialEvaluation::unsetFeasible()
{
    m_FeasibleIsSet = false;
}
utility::datetime MatchTrialEvaluation::getStartedAt() const
{
    return m_StartedAt;
}

void MatchTrialEvaluation::setStartedAt(const utility::datetime& value)
{
    m_StartedAt = value;
    m_StartedAtIsSet = true;
}

bool MatchTrialEvaluation::startedAtIsSet() const
{
    return m_StartedAtIsSet;
}

void MatchTrialEvaluation::unsetStartedAt()
{
    m_StartedAtIsSet = false;
}
utility::datetime MatchTrialEvaluation::getFinishedAt() const
{
    return m_FinishedAt;
}

void MatchTrialEvaluation::setFinishedAt(const utility::datetime& value)
{
    m_FinishedAt = value;
    m_FinishedAtIsSet = true;
}

bool MatchTrialEvaluation::finishedAtIsSet() const
{
    return m_FinishedAtIsSet;
}

void MatchTrialEvaluation::unsetFinishedAt()
{
    m_FinishedAtIsSet = false;
}
}
}
}
}


