/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/ParticipantType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

ParticipantType::eParticipantType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("User")))
        return ParticipantType::eParticipantType::ParticipantType_USER;
    if (val == utility::conversions::to_string_t(U("Team")))
        return ParticipantType::eParticipantType::ParticipantType_TEAM;
    return {};
}

EnumUnderlyingType fromEnum(ParticipantType::eParticipantType e)
{
    switch (e)
    {
    case ParticipantType::eParticipantType::ParticipantType_USER:
        return U("User");
    case ParticipantType::eParticipantType::ParticipantType_TEAM:
        return U("Team");
    default:
        break;
    }
    return {};
}
}

ParticipantType::ParticipantType()
{
}

ParticipantType::~ParticipantType()
{
}

void ParticipantType::validate()
{
    // TODO: implement validation
}

web::json::value ParticipantType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool ParticipantType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void ParticipantType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool ParticipantType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

ParticipantType::eParticipantType ParticipantType::getValue() const
{
   return m_value;
}

void ParticipantType::setValue(ParticipantType::eParticipantType const value)
{
   m_value = value;
}


}
}
}
}


