/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/RunnerStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

RunnerStatus::eRunnerStatus toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("Success")))
        return RunnerStatus::eRunnerStatus::RunnerStatus_SUCCESS;
    if (val == utility::conversions::to_string_t(U("Failed")))
        return RunnerStatus::eRunnerStatus::RunnerStatus_FAILED;
    return {};
}

EnumUnderlyingType fromEnum(RunnerStatus::eRunnerStatus e)
{
    switch (e)
    {
    case RunnerStatus::eRunnerStatus::RunnerStatus_SUCCESS:
        return U("Success");
    case RunnerStatus::eRunnerStatus::RunnerStatus_FAILED:
        return U("Failed");
    default:
        break;
    }
    return {};
}
}

RunnerStatus::RunnerStatus()
{
}

RunnerStatus::~RunnerStatus()
{
}

void RunnerStatus::validate()
{
    // TODO: implement validation
}

web::json::value RunnerStatus::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool RunnerStatus::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void RunnerStatus::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool RunnerStatus::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

RunnerStatus::eRunnerStatus RunnerStatus::getValue() const
{
   return m_value;
}

void RunnerStatus::setValue(RunnerStatus::eRunnerStatus const value)
{
   m_value = value;
}


}
}
}
}


