/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AuthErrorResponse.h
 *
 * Authentication error response
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AuthErrorResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AuthErrorResponse_H_


#include "opthub_api_client/ModelBase.h"

#include "opthub_api_client/model/AuthErrorCode.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Authentication error response
/// </summary>
class  AuthErrorResponse
    : public ModelBase
{
public:
    AuthErrorResponse();
    virtual ~AuthErrorResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AuthErrorResponse members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<AuthErrorCode> getCode() const;
    bool codeIsSet() const;
    void unsetCode();

    void setCode(const std::shared_ptr<AuthErrorCode>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMessage() const;
    bool messageIsSet() const;
    void unsetMessage();

    void setMessage(const utility::string_t& value);


protected:
    std::shared_ptr<AuthErrorCode> m_Code;
    bool m_CodeIsSet;
    utility::string_t m_Message;
    bool m_MessageIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AuthErrorResponse_H_ */
