/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AuthErrorCode.h
 *
 * Authentication error code
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AuthErrorCode_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AuthErrorCode_H_


#include "opthub_api_client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  AuthErrorCode
    : public ModelBase
{
public:
    AuthErrorCode();
    virtual ~AuthErrorCode();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eAuthErrorCode
    {
        AuthErrorCode_APIKEYMISSING,
        AuthErrorCode_INVALIDAPIKEY,
    };

    eAuthErrorCode getValue() const;
    void setValue(eAuthErrorCode const value);

    protected:
        eAuthErrorCode m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AuthErrorCode_H_ */
