/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateMatchTrial_request.h
 *
 * Solution space variable
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CreateMatchTrial_request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CreateMatchTrial_request_H_


#include "opthub_api_client/ModelBase.h"

#include "opthub_api_client/model/ScalarOrVector.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ScalarOrVector;


/// <summary>
/// Solution space variable
/// </summary>
class  CreateMatchTrial_request
    : public ModelBase
{
public:
    CreateMatchTrial_request();
    virtual ~CreateMatchTrial_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateMatchTrial_request members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ScalarOrVector> getVariable() const;
    bool variableIsSet() const;
    void unsetVariable();

    void setVariable(const std::shared_ptr<ScalarOrVector>& value);


protected:
    std::shared_ptr<ScalarOrVector> m_Variable;
    bool m_VariableIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CreateMatchTrial_request_H_ */
