/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetSolutionError.h
 *
 * Failed to retrieve the solution
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_GetSolutionError_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_GetSolutionError_H_


#include "opthub_api_client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  GetSolutionError
    : public ModelBase
{
public:
    GetSolutionError();
    virtual ~GetSolutionError();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eGetSolutionError
    {
        GetSolutionError_INVALIDMATCHID,
        GetSolutionError_INVALIDPARTICIPANTID,
        GetSolutionError_TRIALNOTFOUND,
    };

    eGetSolutionError getValue() const;
    void setValue(eGetSolutionError const value);

    protected:
        eGetSolutionError m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_GetSolutionError_H_ */
