/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MatchTrialStatus.h
 *
 * Types of trial status.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialStatus_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialStatus_H_


#include "opthub_api_client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  MatchTrialStatus
    : public ModelBase
{
public:
    MatchTrialStatus();
    virtual ~MatchTrialStatus();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eMatchTrialStatus
    {
        MatchTrialStatus_EVALUATING,
        MatchTrialStatus_EVALUATOR_FAILED,
        MatchTrialStatus_SCORER_FAILED,
        MatchTrialStatus_SCORING,
        MatchTrialStatus_SUCCESS,
    };

    eMatchTrialStatus getValue() const;
    void setValue(eMatchTrialStatus const value);

    protected:
        eMatchTrialStatus m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialStatus_H_ */
