/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MatchTrialResponse.h
 *
 * Information of the created Solution
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialResponse_H_


#include "opthub_api_client/ModelBase.h"

#include "opthub_api_client/model/MatchTrialStatus.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Information of the created Solution
/// </summary>
class  MatchTrialResponse
    : public ModelBase
{
public:
    MatchTrialResponse();
    virtual ~MatchTrialResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// MatchTrialResponse members

    /// <summary>
    /// Trial number
    /// </summary>
    int32_t getTrialNo() const;
    bool trialNoIsSet() const;
    void unsetTrialNo();

    void setTrialNo(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<MatchTrialStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const std::shared_ptr<MatchTrialStatus>& value);

    /// <summary>
    /// Creation date and time
    /// </summary>
    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();

    void setCreatedAt(const utility::datetime& value);


protected:
    int32_t m_TrialNo;
    bool m_TrialNoIsSet;
    std::shared_ptr<MatchTrialStatus> m_Status;
    bool m_StatusIsSet;
    utility::datetime m_CreatedAt;
    bool m_CreatedAtIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialResponse_H_ */
