/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MatchTrialScore.h
 *
 * Results of Score calculation
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialScore_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialScore_H_


#include "opthub_api_client/ModelBase.h"

#include "opthub_api_client/model/RunnerStatus.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Results of Score calculation
/// </summary>
class  MatchTrialScore
    : public ModelBase
{
public:
    MatchTrialScore();
    virtual ~MatchTrialScore();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// MatchTrialScore members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<RunnerStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const std::shared_ptr<RunnerStatus>& value);

    /// <summary>
    /// Score calculation error information
    /// </summary>
    utility::string_t getError() const;
    bool errorIsSet() const;
    void unsetError();

    void setError(const utility::string_t& value);

    /// <summary>
    /// The value of the Score
    /// </summary>
    double getValue() const;
    bool valueIsSet() const;
    void unsetValue();

    void setValue(double value);

    /// <summary>
    /// Score calculation start date and time
    /// </summary>
    utility::datetime getStartedAt() const;
    bool startedAtIsSet() const;
    void unsetStartedAt();

    void setStartedAt(const utility::datetime& value);

    /// <summary>
    /// Score calculation end date and time
    /// </summary>
    utility::datetime getFinishedAt() const;
    bool finishedAtIsSet() const;
    void unsetFinishedAt();

    void setFinishedAt(const utility::datetime& value);


protected:
    std::shared_ptr<RunnerStatus> m_Status;
    bool m_StatusIsSet;
    utility::string_t m_Error;
    bool m_ErrorIsSet;
    double m_Value;
    bool m_ValueIsSet;
    utility::datetime m_StartedAt;
    bool m_StartedAtIsSet;
    utility::datetime m_FinishedAt;
    bool m_FinishedAtIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialScore_H_ */
