/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ParticipantType.h
 *
 * Participant type
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ParticipantType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ParticipantType_H_


#include "opthub_api_client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  ParticipantType
    : public ModelBase
{
public:
    ParticipantType();
    virtual ~ParticipantType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eParticipantType
    {
        ParticipantType_USER,
        ParticipantType_TEAM,
    };

    eParticipantType getValue() const;
    void setValue(eParticipantType const value);

    protected:
        eParticipantType m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ParticipantType_H_ */
