/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Participant.h
 *
 * Participant information
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Participant_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Participant_H_


#include "opthub_api_client/ModelBase.h"

#include "opthub_api_client/model/ParticipantType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Participant information
/// </summary>
class  Participant
    : public ModelBase
{
public:
    Participant();
    virtual ~Participant();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Participant members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ParticipantType> getParticipantType() const;
    bool participantTypeIsSet() const;
    void unsetParticipantType();

    void setParticipantType(const std::shared_ptr<ParticipantType>& value);


protected:
    std::shared_ptr<ParticipantType> m_ParticipantType;
    bool m_ParticipantTypeIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Participant_H_ */
