/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CompetitionApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_CompetitionApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_CompetitionApi_H_



#include "opthub_api_client/ApiClient.h"
#include "opthub_api_client/ModelBase.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  CompetitionApi 
{
public:

    explicit CompetitionApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~CompetitionApi();

    /// <summary>
    /// Retrieve the competition alias from the competition ID
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id">Competition ID</param>
    pplx::task<utility::string_t> resolveCompetitionAliasById(
        utility::string_t id
    ) const;
    /// <summary>
    /// Retrieve the competition ID from the competition alias
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="alias">Competition alias</param>
    pplx::task<utility::string_t> resolveCompetitionIdByAlias(
        utility::string_t alias
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_CompetitionApi_H_ */

