/**
 * OptHub REST API
 * OptHubの公開REST APIです。
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MatchApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_MatchApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_MatchApi_H_



#include "opthub_api_client/ApiClient.h"
#include "opthub_api_client/ModelBase.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  MatchApi 
{
public:

    explicit MatchApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~MatchApi();

    /// <summary>
    /// 競技IDから競技のエイリアスを取得
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="matchId">競技のID</param>
    pplx::task<utility::string_t> resolveMatchAliasById(
        utility::string_t matchId
    ) const;
    /// <summary>
    /// 競技のエイリアスから競技IDを取得
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="alias">競技のエイリアス</param>
    pplx::task<utility::string_t> resolveMatchIdByAlias(
        utility::string_t alias
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_MatchApi_H_ */

