/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.8.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ParticipantApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ParticipantApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ParticipantApi_H_



#include "opthub_api_client/ApiClient.h"

#include "opthub_api_client/model/Participant.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ParticipantApi 
{
public:

    explicit ParticipantApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ParticipantApi();

    /// <summary>
    /// Retrieve the participant information
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id">Participant ID</param>
    pplx::task<std::shared_ptr<Participant>> getParticipant(
        utility::string_t id
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ParticipantApi_H_ */

